package com.codemetal.tapi.utils;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;

/**
 * This class provides the utilities for this application
 * 
 * @author Amy Tripathi
 *
 */
public class Utils {

	public static final char[] RANDOM_CHARSET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
			.toCharArray();
	public static final int RANDOM_UPPER_LIMIT = 9999;

	/**
	 * This method generates a random number between an upper and a lower bound
	 * value
	 * 
	 * @return the random number generated by the method
	 */
	public static int generateRandomNumber() {
		int lower = 1;
		int upper = Utils.RANDOM_UPPER_LIMIT;
		int result = (int) (Math.random() * (upper - lower)) + lower;
		return result;
	}

	/**
	 * This method gives the current time in milliseconds
	 * 
	 * @return the current time in milliseconds
	 */
	public static long getCurrentTime() {
		long currTime = System.currentTimeMillis();
		return currTime;
	}

	/**
	 * 
	 * @param format
	 *            the format according to which the current date should be
	 *            formatted and returned
	 * @return the current date formatted according to the given format
	 */
	public static String getCurrentDate(String format) {
		SimpleDateFormat dateFormat = new SimpleDateFormat(format);
		return dateFormat.format(new Date());
	}

	/**
	 * 
	 * @param length
	 *            the required length of the random string that is to be
	 *            generated
	 * @return the random string generated with length equal to the specified
	 *         value.
	 */
	public static String generateRandomString(int length) {
		char[] alphabetSet = Utils.RANDOM_CHARSET;
		Random random = new Random();
		StringBuffer out = new StringBuffer(length);
		for (int i = 0; i < length; i++) {

			int index = random.nextInt(alphabetSet.length);

			if (i == 0) {
				while (index <= 9) {
					index = random.nextInt(alphabetSet.length);
				}

			}

			out.append(alphabetSet[index]);

		}
		return out.toString();

	}

}
